// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package taskservice is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Void
	Owner
	Task
	TaskList
*/
package taskservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Owner struct {
	Id    uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Owner) Reset()                    { *m = Owner{} }
func (m *Owner) String() string            { return proto.CompactTextString(m) }
func (*Owner) ProtoMessage()               {}
func (*Owner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Owner) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Owner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Owner) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Task struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Owner       *Owner `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetOwner() *Owner {
	if m != nil {
		return m.Owner
	}
	return nil
}

type TaskList struct {
	Task []*Task `protobuf:"bytes,1,rep,name=task" json:"task,omitempty"`
}

func (m *TaskList) Reset()                    { *m = TaskList{} }
func (m *TaskList) String() string            { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()               {}
func (*TaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskList) GetTask() []*Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "taskservice.Void")
	proto.RegisterType((*Owner)(nil), "taskservice.Owner")
	proto.RegisterType((*Task)(nil), "taskservice.Task")
	proto.RegisterType((*TaskList)(nil), "taskservice.TaskList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error)
	GetTaskList(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TaskList, error)
	UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error)
	DeleteTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) AddTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/taskservice.TaskService/AddTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskList(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TaskList, error) {
	out := new(TaskList)
	err := grpc.Invoke(ctx, "/taskservice.TaskService/GetTaskList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/taskservice.TaskService/UpdateTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/taskservice.TaskService/DeleteTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	AddTask(context.Context, *Task) (*Void, error)
	GetTaskList(context.Context, *Void) (*TaskList, error)
	UpdateTask(context.Context, *Task) (*Void, error)
	DeleteTask(context.Context, *Task) (*Void, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskservice.TaskService/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskservice.TaskService/GetTaskList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskList(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskservice.TaskService/UpdateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskservice.TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskservice.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskService_AddTask_Handler,
		},
		{
			MethodName: "GetTaskList",
			Handler:    _TaskService_GetTaskList_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xbd, 0x6a, 0xc3, 0x30,
	0x10, 0x8e, 0x1d, 0x39, 0x6d, 0x4e, 0x50, 0xe8, 0xd1, 0x82, 0xc9, 0x64, 0x04, 0x05, 0x4f, 0x86,
	0xb8, 0x59, 0x3a, 0x06, 0x0a, 0x5d, 0x0a, 0x05, 0xf7, 0x67, 0x57, 0xa2, 0x1b, 0x8e, 0x24, 0x96,
	0xb1, 0x44, 0xfb, 0xc8, 0x7d, 0x8d, 0x22, 0xb9, 0x84, 0x04, 0x4f, 0xd9, 0x74, 0xdf, 0x7d, 0x7f,
	0xe8, 0x60, 0xae, 0x3b, 0xae, 0xba, 0xde, 0x7a, 0x8b, 0xd2, 0x6b, 0xb7, 0x73, 0xd4, 0x7f, 0xf3,
	0x96, 0xd4, 0x0c, 0xc4, 0x97, 0x65, 0xa3, 0xd6, 0x90, 0xbd, 0xfd, 0xb4, 0xd4, 0xe3, 0x0d, 0xa4,
	0x6c, 0xf2, 0xa4, 0x48, 0x4a, 0xd1, 0xa4, 0x6c, 0x10, 0x41, 0xb4, 0xfa, 0x40, 0x79, 0x5a, 0x24,
	0xe5, 0xbc, 0x89, 0x6f, 0xbc, 0x83, 0x8c, 0x0e, 0x9a, 0xf7, 0xf9, 0x34, 0x82, 0xc3, 0xa0, 0x36,
	0x20, 0x3e, 0xb4, 0xdb, 0x8d, 0x1c, 0x0a, 0x90, 0x86, 0xdc, 0xb6, 0xe7, 0xce, 0xb3, 0x6d, 0xff,
	0x8d, 0x4e, 0x21, 0x2c, 0x21, 0xb3, 0x21, 0x3c, 0xfa, 0xc9, 0x1a, 0xab, 0x93, 0x86, 0x55, 0xac,
	0xd5, 0x0c, 0x04, 0xb5, 0x84, 0xeb, 0x90, 0xf1, 0xca, 0xce, 0xe3, 0x03, 0x88, 0xc0, 0xcb, 0x93,
	0x62, 0x5a, 0xca, 0xfa, 0xf6, 0x4c, 0x14, 0x48, 0x4d, 0x5c, 0xd7, 0xbf, 0x09, 0xc8, 0x30, 0xbe,
	0x0f, 0x2b, 0x5c, 0xc2, 0xd5, 0xda, 0x98, 0xd8, 0x74, 0xac, 0x59, 0x9c, 0x43, 0xf1, 0x6b, 0x26,
	0xf8, 0x04, 0xf2, 0x85, 0xfc, 0x31, 0x78, 0xcc, 0x59, 0xdc, 0x8f, 0x9c, 0x02, 0x53, 0x4d, 0x70,
	0x05, 0xf0, 0xd9, 0x19, 0xed, 0xe9, 0xa2, 0xc0, 0x15, 0xc0, 0x33, 0xed, 0xe9, 0x32, 0xd5, 0x66,
	0x16, 0xef, 0xfb, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x6c, 0x7d, 0x18, 0xec, 0x01, 0x00,
	0x00,
}
