// Code generated by protoc-gen-skel.
// source: api.proto

package main

import (
	"flag"
	"fmt"
	"log"
	"net"

	"grpc/api"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

var (
	port = flag.Int("port", 10000, "The server port")
)

func main() {
	flag.Parse()
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", *port))
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	grpcServer := grpc.NewServer()

	taskservice.RegisterTaskServiceServer(grpcServer, &taskService{})

	grpcServer.Serve(lis)
}

type taskService struct {
	taskList taskservice.TaskList
}

func (t *taskService) AddTask(ctx context.Context, in *taskservice.Task) (*taskservice.Void, error) {
	fmt.Println("AddTask")
	t.taskList.Task = append(t.taskList.Task, in)
	return &taskservice.Void{}, nil
}

func (t *taskService) GetTaskList(ctx context.Context, in *taskservice.Void) (*taskservice.TaskList, error) {
	return &t.taskList, nil
}

func (t *taskService) UpdateTask(ctx context.Context, in *taskservice.Task) (*taskservice.Void, error) {
	return &taskservice.Void{}, nil
}

func (t *taskService) DeleteTask(ctx context.Context, in *taskservice.Task) (*taskservice.Void, error) {
	return &taskservice.Void{}, nil
}
