
// Code generated by protoc-gen-skel.
// source: api.proto

package main

import (
	"flag"
	
	"golang.gurusys.co.uk/apis/streamingservice"
	"golang.gurusys.co.uk/go-framework/server"
	"golang.gurusys.co.uk/go-framework/utils"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"os"
)

var (
	port = flag.Int("port", 10000, "The server port")
)

func main() {
	flag.Parse()
	sd := server.NewServerDef()
	sd.Port = *port
	sd.Register = server.Register(
		func(server *grpc.Server) error {
			e := new(streamingService)
			streamingservice.RegisterStreamingServiceServer(server, e)
			return nil
		},
	)
	err := server.ServerStartup(sd)
	utils.Bail("Unable to start server StreamingServiceServer", err)
	os.Exit(0)
}

type streamingService struct {
}


func (t *streamingService) GetStream(ctx context.Context, in *streamingservice.Void)(*streamingservice.Frame, error) {
    return nil,nil
}
