
// Code generated by protoc-gen-skel.
// source: api.proto

package main

import (
	"flag"
	"golang.gurusys.co.uk/apis/streamingservice"
	"golang.gurusys.co.uk/go-framework/client"
	"golang.gurusys.co.uk/go-framework/tokens"
	"golang.gurusys.co.uk/go-framework/utils"
	"golang.org/x/net/context"
	"os"
)

func main() {
	flag.Parse()

	dialer := client.NewDialer()

	err := dialer.DialService("streamingservice.StreamingService")

	utils.Bail("Connection to the StreamingService failed: %s\n", err)

	dialer.RLock()
	defer dialer.RUnlock()

	streamingServiceClient := streamingservice.NewStreamingServiceClient(dialer.GetConn())

	ctx := tokens.ContextWithToken()

	_ = ctx
	_ = streamingServiceClient
	
	os.Exit(0)
}


func testGetStream(ctx context.Context, streamingServiceClient streamingservice.StreamingServiceClient){
	input := streamingservice.Void{}
	//output := streamingservice.Frame{}
	output,err := streamingServiceClient.GetStream(ctx, &input)

	_ = output
	_ = err
}
