
// Code generated by protoc-gen-skel.
// source: api.proto

package main

import (
	"flag"
	
	"golang.gurusys.co.uk/apis/taskservice"
	"golang.gurusys.co.uk/go-framework/server"
	"golang.gurusys.co.uk/go-framework/utils"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"os"
)

var (
	port = flag.Int("port", 10000, "The server port")
)

func main() {
	flag.Parse()
	sd := server.NewServerDef()
	sd.Port = *port
	sd.Register = server.Register(
		func(server *grpc.Server) error {
			e := new(taskService)
			taskservice.RegisterTaskServiceServer(server, e)
			return nil
		},
	)
	err := server.ServerStartup(sd)
	utils.Bail("Unable to start server TaskServiceServer", err)
	os.Exit(0)
}

type taskService struct {
}


func (t *taskService) AddTask(ctx context.Context, in *taskservice.Task)(*taskservice.Void, error) {
    return nil,nil
}

func (t *taskService) GetTaskList(ctx context.Context, in *taskservice.Void)(*taskservice.TaskList, error) {
    return nil,nil
}

func (t *taskService) UpdateTask(ctx context.Context, in *taskservice.Task)(*taskservice.Void, error) {
    return nil,nil
}

func (t *taskService) DeleteTask(ctx context.Context, in *taskservice.Task)(*taskservice.Void, error) {
    return nil,nil
}
